apiVersion: v1
kind: Namespace
metadata:
  name: imac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: imac
subjects:
  - kind: ServiceAccount
    namespace: imac
    name: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  namespace: imac
  name: imac
spec:
  containers:
    - name: defn
      image: defn/defn
      tty: true
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: password-store
          mountPath: /home/ubuntu/.password-store
        - name: kube
          mountPath: /home/ubuntu/.kube
        - name: work
          mountPath: /workspaces
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    - name: password-store
      hostPath:
        path: /mnt/password-store
    - name: kube
      hostPath:
        path: /mnt/kube
    - name: work
      hostPath:
        path: /mnt/work
