allow_k8s_contexts('k3d-roke')

docker_build('defn/defn', '.')
k8s_yaml('main.yaml')

load('ext://uibutton', 'cmd_button', 'location', 'text_input')

cmd_button(name='vscode',
           argv=['code', '--folder-uri', 'vscode-remote://k8s-container+context=k3d-roke+namespace=roke+podname=roke+name=defn+image=defn++/workspaces/defn/app/admin/imma'],
           text='Launch VSCode',
           location=location.NAV,
           icon_name='waving_hand')
