analytics_settings(False)

allow_k8s_contexts('k3d-mini')

docker_build('defn/defn', '.')
k8s_yaml('main.yaml')

load('ext://uibutton', 'cmd_button', 'location', 'text_input')

cmd_button(name='vscode',
           argv=['code', '--folder-uri', 'vscode-remote://k8s-container+context=k3d-mini+namespace=mini+podname=mini+name=defn+image=defn++/workspaces'],
           text='Launch VSCode',
           location=location.NAV,
           icon_name='waving_hand')

cmd_button(name='cilium',
           argv=['cilium', 'hubble', 'ui'],
           text='Launch Cilium',
           location=location.NAV,
           icon_name='waving_hand')

cmd_button(name='linkerd',
           argv=['linkerd', 'viz', 'dashboard'],
           text='Launch Linkerd',
           location=location.NAV,
           icon_name='waving_hand')

local_resource('vscode',
    cmd='code --folder-uri vscode-remote://k8s-container+context=k3d-mini+namespace=mini+podname=mini+name=defn+image=defn++/workspaces',
    resource_deps=['mini'])
