apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: zero
servers: 1
agents: 0
kubeAPI:
  host: zero.defn.ooo
  hostIP: 0.0.0.0
image: rancher/k3s:v1.22.8-k3s1
hostAliases:
  - ip: 100.101.28.35
    hostnames:
      - this
volumes:
  - volume: /var/run/docker.sock:/var/run/docker.sock
    nodeFilters:
      - server:0
  - volume: k3d-password-store:/mnt/password-store
    nodeFilters:
      - server:0
  - volume: k3d-kube:/mnt/kube
    nodeFilters:
      - server:0
  - volume: k3d-work:/mnt/work
    nodeFilters:
      - server:0
options:
  k3d:
    wait: true
    timeout: 360s
    disableLoadbalancer: false
  k3s:
    extraArgs:
      - arg: --tls-san=100.101.28.35
        nodeFilters:
          - server:0
      - arg: --tls-san=zero.defn.ooo
        nodeFilters:
          - server:0
      - arg: --disable=traefik
        nodeFilters:
          - server:0
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: false
registries:
  use:
    - k3d-registry.localhost:5555
